// Code automatically generated by perplex.

/// All nonterminals that may be pushed onto the stack.
enum Nonterminal {
    Nt0(ast::Desc),
    Nt1(ast::Item),
    Nt2(ast::TokenDecl),
    Nt3(ast::RuleDecl),
    Nt4(Vec<Vec<String>>),
    Nt5(Vec<String>),
}

impl Nonterminal {
    #[inline(always)]
    fn unwrap_nt0(self) -> ast::Desc {
        match self {
            Nonterminal::Nt0(nt) => nt,
            _ => panic!("expected nonterminal `ast::Desc`"),
        }
    }
    #[inline(always)]
    fn unwrap_nt1(self) -> ast::Item {
        match self {
            Nonterminal::Nt1(nt) => nt,
            _ => panic!("expected nonterminal `ast::Item`"),
        }
    }
    #[inline(always)]
    fn unwrap_nt2(self) -> ast::TokenDecl {
        match self {
            Nonterminal::Nt2(nt) => nt,
            _ => panic!("expected nonterminal `ast::TokenDecl`"),
        }
    }
    #[inline(always)]
    fn unwrap_nt3(self) -> ast::RuleDecl {
        match self {
            Nonterminal::Nt3(nt) => nt,
            _ => panic!("expected nonterminal `ast::RuleDecl`"),
        }
    }
    #[inline(always)]
    fn unwrap_nt4(self) -> Vec<Vec<String>> {
        match self {
            Nonterminal::Nt4(nt) => nt,
            _ => panic!("expected nonterminal `Vec<Vec<String>>`"),
        }
    }
    #[inline(always)]
    fn unwrap_nt5(self) -> Vec<String> {
        match self {
            Nonterminal::Nt5(nt) => nt,
            _ => panic!("expected nonterminal `Vec<String>`"),
        }
    }
}

impl ::std::fmt::Debug for Nonterminal {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match *self {
            Nonterminal::Nt0(..) => write!(f, "desc"),
            Nonterminal::Nt1(..) => write!(f, "item"),
            Nonterminal::Nt2(..) => write!(f, "token_decl"),
            Nonterminal::Nt3(..) => write!(f, "rule_decl"),
            Nonterminal::Nt4(..) => write!(f, "rule_list"),
            Nonterminal::Nt5(..) => write!(f, "sequence"),
        }
    }
}

fn state_0<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        Some(Token::Ident(_)) => p.shift(state_7, reduced_7),
        Some(Token::Keyword(Keyword::Token)) => p.shift(state_6, reduced_6),
        Some(Token::Semicolon) => p.shift(state_3, reduced_3),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_0<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        Nonterminal::Nt0(..) => p.goto(nt, state_1, reduced_1),
        Nonterminal::Nt1(..) => p.goto(nt, state_2, reduced_2),
        Nonterminal::Nt2(..) => p.goto(nt, state_4, reduced_4),
        Nonterminal::Nt3(..) => p.goto(nt, state_5, reduced_5),
        _ => unreachable!(),
    };
}

fn state_1<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        None => p.accept(),
        Some(Token::Ident(_)) => p.shift(state_7, reduced_7),
        Some(Token::Keyword(Keyword::Token)) => p.shift(state_6, reduced_6),
        Some(Token::Semicolon) => p.shift(state_9, reduced_9),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_1<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        Nonterminal::Nt1(..) => p.goto(nt, state_8, reduced_8),
        Nonterminal::Nt2(..) => p.goto(nt, state_4, reduced_4),
        Nonterminal::Nt3(..) => p.goto(nt, state_5, reduced_5),
        _ => unreachable!(),
    };
}

fn state_2<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        None => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt1();
            let reduced: ast::Desc = reduce_desc_b(
                arg0,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Ident(_)) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt1();
            let reduced: ast::Desc = reduce_desc_b(
                arg0,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Keyword(Keyword::Token)) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt1();
            let reduced: ast::Desc = reduce_desc_b(
                arg0,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Semicolon) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt1();
            let reduced: ast::Desc = reduce_desc_b(
                arg0,
            );
            Nonterminal::Nt0(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_2<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_3<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        None => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::Desc = reduce_desc_d(
                arg0,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Ident(_)) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::Desc = reduce_desc_d(
                arg0,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Keyword(Keyword::Token)) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::Desc = reduce_desc_d(
                arg0,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Semicolon) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::Desc = reduce_desc_d(
                arg0,
            );
            Nonterminal::Nt0(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_3<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_4<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        None => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt2();
            let reduced: ast::Item = reduce_item_a(
                arg0,
            );
            Nonterminal::Nt1(reduced)
        }),
        Some(Token::Ident(_)) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt2();
            let reduced: ast::Item = reduce_item_a(
                arg0,
            );
            Nonterminal::Nt1(reduced)
        }),
        Some(Token::Keyword(Keyword::Token)) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt2();
            let reduced: ast::Item = reduce_item_a(
                arg0,
            );
            Nonterminal::Nt1(reduced)
        }),
        Some(Token::Semicolon) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt2();
            let reduced: ast::Item = reduce_item_a(
                arg0,
            );
            Nonterminal::Nt1(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_4<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_5<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        None => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt3();
            let reduced: ast::Item = reduce_item_b(
                arg0,
            );
            Nonterminal::Nt1(reduced)
        }),
        Some(Token::Ident(_)) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt3();
            let reduced: ast::Item = reduce_item_b(
                arg0,
            );
            Nonterminal::Nt1(reduced)
        }),
        Some(Token::Keyword(Keyword::Token)) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt3();
            let reduced: ast::Item = reduce_item_b(
                arg0,
            );
            Nonterminal::Nt1(reduced)
        }),
        Some(Token::Semicolon) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt3();
            let reduced: ast::Item = reduce_item_b(
                arg0,
            );
            Nonterminal::Nt1(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_5<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_6<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        Some(Token::Ident(_)) => p.shift(state_10, reduced_10),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_6<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_7<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        Some(Token::Colon) => p.shift(state_11, reduced_11),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_7<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_8<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        None => p.reduce(2, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt0();
            let arg1 = args.next().unwrap().unwrap_nonterminal().unwrap_nt1();
            let reduced: ast::Desc = reduce_desc_a(
                arg0,
                arg1,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Ident(_)) => p.reduce(2, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt0();
            let arg1 = args.next().unwrap().unwrap_nonterminal().unwrap_nt1();
            let reduced: ast::Desc = reduce_desc_a(
                arg0,
                arg1,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Keyword(Keyword::Token)) => p.reduce(2, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt0();
            let arg1 = args.next().unwrap().unwrap_nonterminal().unwrap_nt1();
            let reduced: ast::Desc = reduce_desc_a(
                arg0,
                arg1,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Semicolon) => p.reduce(2, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt0();
            let arg1 = args.next().unwrap().unwrap_nonterminal().unwrap_nt1();
            let reduced: ast::Desc = reduce_desc_a(
                arg0,
                arg1,
            );
            Nonterminal::Nt0(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_8<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_9<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        None => p.reduce(2, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt0();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::Desc = reduce_desc_c(
                arg0,
                arg1,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Ident(_)) => p.reduce(2, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt0();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::Desc = reduce_desc_c(
                arg0,
                arg1,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Keyword(Keyword::Token)) => p.reduce(2, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt0();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::Desc = reduce_desc_c(
                arg0,
                arg1,
            );
            Nonterminal::Nt0(reduced)
        }),
        Some(Token::Semicolon) => p.reduce(2, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt0();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::Desc = reduce_desc_c(
                arg0,
                arg1,
            );
            Nonterminal::Nt0(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_9<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_10<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        Some(Token::Semicolon) => p.shift(state_12, reduced_12),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_10<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_11<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        Some(Token::Ident(_)) => p.shift(state_15, reduced_15),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_11<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        Nonterminal::Nt4(..) => p.goto(nt, state_13, reduced_13),
        Nonterminal::Nt5(..) => p.goto(nt, state_14, reduced_14),
        _ => unreachable!(),
    };
}

fn state_12<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        None => p.reduce(3, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let arg2 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::TokenDecl = reduce_token_decl(
                arg0,
                arg1,
                arg2,
            );
            Nonterminal::Nt2(reduced)
        }),
        Some(Token::Ident(_)) => p.reduce(3, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let arg2 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::TokenDecl = reduce_token_decl(
                arg0,
                arg1,
                arg2,
            );
            Nonterminal::Nt2(reduced)
        }),
        Some(Token::Keyword(Keyword::Token)) => p.reduce(3, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let arg2 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::TokenDecl = reduce_token_decl(
                arg0,
                arg1,
                arg2,
            );
            Nonterminal::Nt2(reduced)
        }),
        Some(Token::Semicolon) => p.reduce(3, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let arg2 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::TokenDecl = reduce_token_decl(
                arg0,
                arg1,
                arg2,
            );
            Nonterminal::Nt2(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_12<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_13<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        Some(Token::Semicolon) => p.shift(state_16, reduced_16),
        Some(Token::Pipe) => p.shift(state_17, reduced_17),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_13<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_14<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        Some(Token::Ident(_)) => p.shift(state_18, reduced_18),
        Some(Token::Semicolon) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt5();
            let reduced: Vec<Vec<String>> = reduce_rule_list_b(
                arg0,
            );
            Nonterminal::Nt4(reduced)
        }),
        Some(Token::Pipe) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt5();
            let reduced: Vec<Vec<String>> = reduce_rule_list_b(
                arg0,
            );
            Nonterminal::Nt4(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_14<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_15<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        Some(Token::Ident(_)) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let reduced: Vec<String> = reduce_sequence_b(
                arg0,
            );
            Nonterminal::Nt5(reduced)
        }),
        Some(Token::Semicolon) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let reduced: Vec<String> = reduce_sequence_b(
                arg0,
            );
            Nonterminal::Nt5(reduced)
        }),
        Some(Token::Pipe) => p.reduce(1, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let reduced: Vec<String> = reduce_sequence_b(
                arg0,
            );
            Nonterminal::Nt5(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_15<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_16<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        None => p.reduce(4, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let arg2 = args.next().unwrap().unwrap_nonterminal().unwrap_nt4();
            let arg3 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::RuleDecl = reduce_rule_decl(
                arg0,
                arg1,
                arg2,
                arg3,
            );
            Nonterminal::Nt3(reduced)
        }),
        Some(Token::Ident(_)) => p.reduce(4, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let arg2 = args.next().unwrap().unwrap_nonterminal().unwrap_nt4();
            let arg3 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::RuleDecl = reduce_rule_decl(
                arg0,
                arg1,
                arg2,
                arg3,
            );
            Nonterminal::Nt3(reduced)
        }),
        Some(Token::Keyword(Keyword::Token)) => p.reduce(4, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let arg2 = args.next().unwrap().unwrap_nonterminal().unwrap_nt4();
            let arg3 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::RuleDecl = reduce_rule_decl(
                arg0,
                arg1,
                arg2,
                arg3,
            );
            Nonterminal::Nt3(reduced)
        }),
        Some(Token::Semicolon) => p.reduce(4, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_terminal();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let arg2 = args.next().unwrap().unwrap_nonterminal().unwrap_nt4();
            let arg3 = args.next().unwrap().unwrap_terminal();
            let reduced: ast::RuleDecl = reduce_rule_decl(
                arg0,
                arg1,
                arg2,
                arg3,
            );
            Nonterminal::Nt3(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_16<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_17<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        Some(Token::Ident(_)) => p.shift(state_15, reduced_15),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_17<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        Nonterminal::Nt5(..) => p.goto(nt, state_19, reduced_19),
        _ => unreachable!(),
    };
}

fn state_18<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        Some(Token::Ident(_)) => p.reduce(2, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt5();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let reduced: Vec<String> = reduce_sequence_a(
                arg0,
                arg1,
            );
            Nonterminal::Nt5(reduced)
        }),
        Some(Token::Semicolon) => p.reduce(2, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt5();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let reduced: Vec<String> = reduce_sequence_a(
                arg0,
                arg1,
            );
            Nonterminal::Nt5(reduced)
        }),
        Some(Token::Pipe) => p.reduce(2, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt5();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let reduced: Vec<String> = reduce_sequence_a(
                arg0,
                arg1,
            );
            Nonterminal::Nt5(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_18<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}

fn state_19<P>(p: &mut P) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match *p.peek() {
        Some(Token::Ident(_)) => p.shift(state_18, reduced_18),
        Some(Token::Semicolon) => p.reduce(3, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt4();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let arg2 = args.next().unwrap().unwrap_nonterminal().unwrap_nt5();
            let reduced: Vec<Vec<String>> = reduce_rule_list_a(
                arg0,
                arg1,
                arg2,
            );
            Nonterminal::Nt4(reduced)
        }),
        Some(Token::Pipe) => p.reduce(3, |args|{
            let mut args = args.into_iter();
            let arg0 = args.next().unwrap().unwrap_nonterminal().unwrap_nt4();
            let arg1 = args.next().unwrap().unwrap_terminal();
            let arg2 = args.next().unwrap().unwrap_nonterminal().unwrap_nt5();
            let reduced: Vec<Vec<String>> = reduce_rule_list_a(
                arg0,
                arg1,
                arg2,
            );
            Nonterminal::Nt4(reduced)
        }),
        _ => panic!("syntax error, unexpected {:?}", p.peek()),
    };
}

fn reduced_19<P>(p: &mut P, nt: Nonterminal) where P: Parser<Terminal = Terminal, Nonterminal = Nonterminal> {
    match nt {
        _ => unreachable!(),
    };
}
